apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: innowise
data:
  application.properties: |
    user.service.url=http://user-service:8080
    auth.service.url=http://auth-service:8079
    order.service.url=http://order-service:8078
    payment.service.url=http://payment-service:8077
    gateway.public-paths=/auth/login,/auth/registration,/auth/refresh
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: innowise
type: Opaque
stringData:
  jwt-secret-access: "U2VjcmV0S2V5Rm9yQWNjZXNzVG9rZW5BdXRoU2VydmljZQ=="
