apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: innowise
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: pandarick9/authenticationservice:77a9994255c994915fbe51b41ab71a16120120ab
          ports:
            - containerPort: 8079
          env:
            - name: SERVER_PORT
              value: "8079"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-auth:5432/auth_service"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Postgres_9"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none"
            - name: SPRING_LIQUIBASE_ENABLED
              value: "true"
            - name: JWT_SECRET_ACCESS
              value: "U2VjcmV0S2V5Rm9yQWNjZXNzVG9rZW5BdXRoU2VydmljZQ=="
            - name: JWT_SECRET_REFRESH
              value: "U2VjcmV0S2V5Rm9yUmVmcmVzaFRva2VuQXV0aFNlcnZpY2U="
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: innowise
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8079
      targetPort: 8079
---
