apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: innowise
data:
  SERVER_PORT: "8079"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-auth:5432/auth_service"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_LIQUIBASE_ENABLED: "true"
  SPRING_PROFILES_ACTIVE: "local"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: innowise
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "Postgres_9"
  JWT_SECRET_ACCESS: "U2VjcmV0S2V5Rm9yQWNjZXNzVG9rZW5BdXRoU2VydmljZQ=="
  JWT_SECRET_REFRESH: "U2VjcmV0S2V5UmVmcmVzaFRva2VuQXV0aFNlcnZpY2U="
