apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: innowise
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: pandarick9/userservice:2e3e5d6609b8709c63d19ad72e404c109cc977b0
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-user:5432/user_service"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Postgres_9"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none"
            - name: SPRING_LIQUIBASE_ENABLED
              value: "true"
            - name: JWT_SECRET_ACCESS
              value: "U2VjcmV0S2V5Rm9yQWNjZXNzVG9rZW5BdXRoU2VydmljZQ=="
            - name: SPRING_CACHE_TYPE
              value: "redis"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---


apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: innowise
  labels:
    app: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080