apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: innowise
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdHVzZXI=
  MONGO_INITDB_ROOT_PASSWORD: cm9vdHBhc3M=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: innowise
data:
  MONGO_INITDB_DATABASE: "payment_db"
