apiVersion: v1
kind: Namespace
metadata:
  name: innowise
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-secret
  namespace: innowise
type: Opaque
data:
  POSTGRES_PASSWORD: UG9zdGdyZXNfOQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-user-config
  namespace: innowise
data:
  POSTGRES_DB: "user_service"
  POSTGRES_USER: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user
  namespace: innowise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-user-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-user-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-user-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-user-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user
  namespace: innowise
spec:
  type: ClusterIP
  selector:
    app: postgres-user
  ports:
    - port: 5432
      targetPort: 5432
