apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: innowise
type: Opaque
data:
  POSTGRES_PASSWORD: UG9zdGdyZXNfOQ==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-auth-config
  namespace: innowise
data:
  POSTGRES_DB: "auth_service"
  POSTGRES_USER: "postgres"